verbose: false
instrumentation:
  root: lib
  extensions:
    - .ts
#   default-excludes: true
#   excludes: []
#   variable: __coverage__
#   compact: true
#   preserve-comments: false
#   complete-copy: false
#   save-baseline: false
#   baseline-file: ./coverage/coverage-baseline.raw.json
#   include-all-sources: false
#   include-pid: false
#   es-modules: true
#   auto-wrap: true
# reporting:
#   print: summary
#   reports:
#     - lcov
#   dir: ./coverage
#   summarizer: pkg
#   report-config: {}
#   watermarks:
#     statements: [50, 80]
#     functions: [50, 80]
#     branches: [50, 80]
#     lines: [50, 80]
# hooks:
#   hook-run-in-context: false
#   post-require-hook: null
#   handle-sigint: false
# check:
#   global:
#     statements: 0
#     lines: 0
#     branches: 0
#     functions: 0
#     excludes: []
#     each:
#       statements: 0
#       lines: 0
#       branches: 0
#       functions: 0
#       excludes: []
